name = "JuliaProjectTemplate"
uuid = "5821695c-2820-464b-a8b2-f88be83063f5"
authors = ["Javier González Monge"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
